service: eventService
provider:
  name: aws
  runtime: nodejs6.10
functions:
  getEvents:
    handler: handler.getEvents
    events:
         - http:
             path: /events
             method: get
  getEvent:
    handler: handler.getEvent
    events:
         - http:
             path: /event/{id}
             method: get
plugins:
  - serverless-dynamodb-local
  - serverless-offline
